name: Deploy my page

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build-run-tests:
    name: Deploy my page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: nodejs setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: yarn install and build
        run: |
          yarn install
          yarn build

      - name: Save page
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build-run-tests

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
