name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Astro
        run: yarn build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
